_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.30.0
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 4
dataset_dir:
    value: processed_data
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 5e-05
lora_alpha:
    value: 16
lora_dropout:
    value: 0.05
lora_r:
    value: 8
max_source_length:
    value: 512
max_target_length:
    value: 256
model_name_or_path:
    value: google/flan-t5-base
num_epochs:
    value: 20
output_dir:
    value: ./api-docs-model
quantization:
    value: none
seed:
    value: 42
use_wandb:
    value: true
wandb_project:
    value: doc-optimizer
warmup_ratio:
    value: 0.1
weight_decay:
    value: 0.01
