_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.30.0
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 1
epochs:
    value: 100
learning_rate:
    value: 0.001
lora_alpha:
    value: 32
lora_dropout:
    value: 0.1
lora_r:
    value: 32
max_source_length:
    value: 512
max_target_length:
    value: 512
model:
    value: google/flan-t5-base
quantization:
    value: none
